# ADMIN SERVICE

### Events
GET http://localhost:4004/admin/Events

###
POST http://localhost:4004/admin/Events
Content-Type: application/json

{
    "name": "New Event",
    "description": "New Description",
    "startDate": "2020-01-01",
    "endDate": "2020-01-02"
}

###
PATCH http://localhost:4004/admin/Events(cf96d4d0-f1e1-4b80-ba90-ddad0c32676e)
Content-Type: application/json

{
    "name": "Newer Event",
    "description": "New Description",
    "startDate": "2020-01-01",
    "endDate": "2020-01-02"
}

###
DELETE http://localhost:4004/admin/Events(eed460e6-25d4-480d-983a-a2ad12bda552)

